import pygame

def setup(screen, ALIVE_COLOR, CELL_SIZE):
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(10*5,30*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(11*5,30*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(10*5,31*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(11*5,31*5, CELL_SIZE, CELL_SIZE))

    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(23*5,27*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(22*5,27*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(21*5,28*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(20*5,29*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(20*5,30*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(20*5,31*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(21*5,32*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(22*5,33*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(23*5,33*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(24*5,30*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(25*5,28*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(25*5,32*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(26*5,29*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(26*5,30*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(26*5,31*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(27*5,30*5, CELL_SIZE, CELL_SIZE))

    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(30*5,29*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(30*5,28*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(30*5,27*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(31*5,29*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(31*5,28*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(31*5,27*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(32*5,30*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(32*5,26*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(34*5,26*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(34*5,25*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(34*5,30*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(34*5,31*5, CELL_SIZE, CELL_SIZE))

    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(44*5,28*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(44*5,27*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(45*5,28*5, CELL_SIZE, CELL_SIZE))
    pygame.draw.rect(screen,ALIVE_COLOR,pygame.Rect(45*5,27*5, CELL_SIZE, CELL_SIZE))